name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ubuntu-20.04, windows-2019, macos-10.15]
        os: [ubuntu-20.04, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Setup requirements
        run: pip install -r requirements.txt

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        # to supply options, put them in 'env', like:
        env:
          # install something required for the build (you might want to use pyproject.toml instead)
          CIBW_BEFORE_BUILD: pip install pybind11
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
